version: "3.1"

services:

  redis:
    image: redis:5.0
    restart: always
    ports:
      - "6279:6379"

  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "26017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mypassword
